default:
  outputs:

    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      dataset: "{{ var('bq_dataset_name') }}"
      threads: 1
      timeout_seconds: 300
      priority: interactive
      retries: 1

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      dataset: "{{ var('bq_dataset_name') }}"
      threads: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      timeout_seconds: 300
      priority: interactive
      retries: 1

  target: dev