version: "3"

services:
  devenv:
    build: .
    volumes:
      - devenv:/root
      - .:/app/repo
      - ~/.aws:/root/.aws
      - ~/.config:/root/.config
      - ~/.ssh:/root/.ssh
    environment:
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - GOOGLE_CLOUD_PROJECT
    ports:
      - 4000:4000
    tty: true
volumes:
  devenv: