version: "3"

services:
  devenv:
    build: .
    volumes:
      - .:/repo
      - ~/.aws:/root/.aws
      - ~/.config:/root/.config
    environment:
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - GOOGLE_CLOUD_PROJECT
    tty: true
