
version: 2

models:
    - name: jasso_gakuseiseikatsu_stats_annual_income_divide_university_type_and_income
      description: "Annual income of univercity student house divide university and income."
      columns:
          - name: university_type
            description: "University type"
          - name: year
            description: "Stat year"
          - name: quintile
            description: "quintile name"
          - name: value
            description: "quintile average annual income"
            tests:
              - is_over:
                  criteria: 0
