source 'https://rubygems.org'

gem "jekyll"
gem "minimal-mistakes-jekyll"
group :jekyll_plugins do
    gem "github-pages", "~> 217"
    gem "jekyll-include-cache"
    gem "jekyll-seo-tag"
    gem "jekyll-paginate-v2"
end