name: CD CHECK
on:
  workflow_run:
    workflows:
      - CD
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v4
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            workflow = github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            })
            console.log(workflow)
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: workflow.issue.number
            })
      - uses: actions/github-script@v4
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            workflow = github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            })
            console.log(workflow)
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: workflow.issue.number,
              name: 'apply'
            })
