name: CD CHECK
on:
  workflow_run:
    workflows:
      - CD
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "${{ toJSON(github.event) }}"
      - uses: actions/github-script@v4
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
          ISSUE_NUMBER: ${{ github.event.pull_requests[0].number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: process.env.ISSUE_NUMBER
            })
      - uses: actions/github-script@v4
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        env:
          ISSUE_NUMBER: ${{ github.event.pull_requests[0].number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(process.env.ISSUE_NUMBER)
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: process.env.ISSUE_NUMBER,
              name: 'apply'
            })
