name: CD CHECK
on:
  workflow_run:
    workflows:
      - CD
    types:
      - completed

jobs:
  merge_branch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v4
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
      - uses: actions/github-script@v4
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
              name: 'apply'
            })